version: '3.8'
volumes:
    postgres_data: {}

services: 
    app:
        build: 
            context: .
            dockerfile: ./compose/app/Dockerfile
        env_file:
            - ./.env
        ports:
            - 80:80
        depends_on: 
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
